testdata/in/continue_in_defer.nen:3:3: invalid continue outside a loop
